### ISSUE TITLE
Test Rig

### ISSUE THREAD

**Issue by NikolaiRuhe** [savoyhardwaregroup/speedometer#2]
Create a test rig with an actual hub dynamo. A motor to drive the dynamo and adjustable load would be nice.

**Comment by ole** [comment]
Mein Fahrradhändler hat mir einen alten Nabendynamo geschenkt. Für den Testaufbau müssen wir uns in der Tat noch etwas überlegen. Man muss den Dynamo an den Achsenden ziemlich festklemmen/-schrauben, damit man ihn vernünftig drehen kann.

Es handelt sich um dieses Modell: [Shimano DH-3N32-NT](https://www.bike-discount.de/de/kaufen/shimano-dh-3n31-nt-nabendynamo-36-loch-731913)

Einbaumaß: 100 mm
Achse: Vollachse (kein Schnellspanner), Gewinde M9

Ein Patentrezept, wie wir das am besten machen, habe ich noch nicht.

Foto:

![img_2048](https://user-images.githubusercontent.com/5010/53355639-c13db580-3929-11e9-8efd-9cc1ab06a2e1.jpg)

**Comment by NikolaiRuhe** [comment]
Hier ist eine [Explosionszeichnung](https://si.shimano.com/pdfs/ev/EV-DH-3N31-NT-3545.pdf).

**Comment by NikolaiRuhe** [comment]
Auf dem Bild sieht es so aus, als ob Dein Modell die 36 Loch (18 Speichen pro Flansch) Variante ist. Kannst Du das bestätigen, @ole?

**Comment by ole** [comment]
Ja, 36 Speichen ist korrekt.

**Comment by ole** [comment]
Hier ein Video von einem professionellen Test Rig auf einem Messestand: 
https://www.youtube.com/watch?v=frzVUkbe9BA

Die treiben den Dynamo über einen Keilriemen an, der Motor scheint unter dem Tisch zu sein. Die Verbindung vom Antriebsrad zum Dynamo scheint über die Scheibenbremsaufnahme des Dynamos zu laufen (wo normalerweise die Bremsscheibe montiert wird). Unser Dynamo hat keine Scheibenbremsaufnahme, aber @jjac meinte, man könnte ggf. die Speichenlöcher für etwas ähnliches verwenden.

![screen shot 2019-02-28 at 11 50 00](https://user-images.githubusercontent.com/5010/53561380-04c53900-3b4f-11e9-99b2-b07cf8bb15a8.png)

**Comment by NikolaiRuhe** [comment]
Ich habe mal gerechnet: Der Dynamo erzeugt nominal 3W, vielleicht 5W unter idealen Bedingungen. Wenn der Wirkungsgrad 50% ist (hoch geschätzt) muss die Achse mit mindestens 10W Motorleistung angetrieben werden. Wenn man noch Reibungsverluste und den Wirkungsgrad des Antriebs einrechnet, muss der Motor mindestens 20–30W Anschlussleistung haben.

So einen habe ich nicht hier. Daher habe ich erst mal eine Kurbel ausgedruckt, die direkt auf den Flansch geschraubt wird:

![img_6911](https://user-images.githubusercontent.com/640896/53564118-4c02f800-3b56-11e9-9250-854c2c2adc96.JPG)

Müssen wir uns halt beim Kurbeln abwechseln :)

**Comment by ole** [comment]
Wow, sieht super aus!

**Comment by jjac** [comment]
Cool! Sehr schöne Minimalversion.

Ich habe noch zwei motor-getriebene Varianten im Kopf, die kann ich morgen erläutern.

**Comment by jjac** [comment]
Ich habe eine meiner Überlegungen dazu mal skizziert:

![hardware projects - 2019-03-01 04 20 15](https://user-images.githubusercontent.com/420542/53622856-75c22a80-3bfb-11e9-97cd-191629160179.jpg)

Die Aufhängung für den Dynamo habe ich in der perspektivischen Ansicht weggelassen. Als Antriebsrad könnten wir wahrscheinlich [etwas von der Stange nehmen](https://www.otto.de/p/holzrad-mit-gummireifen-o-ca-85-mm-565765065/#variationId=752866195). Bei dieser skizzierten Variante ist zu berücksichtigen, dass eine nicht unerhebliche seitliche Kraft auf die Antriebswelle wirken wird, die der Antriebsmotor auch verkraften muss.

Eine alternative nicht skizzierte Überlegung geht dahin, die Kraft auf den Dynamo per Zahnrad zu übertragen. Dadurch entfiele die seitliche Kraft auf die Antriebswelle. Ein Zahnkranz wäre (ähnlich zu Nikolais Kurbel) auf den Dynamo geschraubt, auf die Motorwelle würde statt eines Rades ein Zahnrad gesetzt. So könnte man auch eine Getriebeunter- oder übersetzung besser zuschneiden.

Die Motordrehzahl sollte idealerweise (stufenlos) über einen Regler einstellbar sein. Ich weiß jedoch nicht, ob das einfach umzusetzen ist.

**Comment by ole** [comment]
@jjac Sehr schicke Zeichnung! Finde ich super.

**Comment by NikolaiRuhe** [comment]
Ich denke, die aktuelle Variante mit Akkuschrauber reicht fürs erste.
