### ISSUE TITLE
Aktuelle Marktübersicht Dynamo-USB-Lader mit Pufferakku

### ISSUE THREAD

**Issue by ole** [savoyhardwaregroup/speedometer#24]
Das ist nicht ganz unser Gebiet, aber in der neuen Ausgabe des hervorragenden Magazins Fahrradzukunft ist [ein aktueller Test der gängigen Dynamo-Ladegeräte](https://fahrradzukunft.de/28/steckdose-unterwegs-7/). Ich finde es ganz schön heftig, dass die High-End-Geräte teilweise über 200 € kosten. Viele Leute kaufen dafür ein ganzes Fahrrad.

**Comment by NikolaiRuhe** [comment]
... und viele Leute kaufen einen Tachometer für 10 Euro – statt wochenlang an einem Gerät zu basteln, das es schon gibt :)

**Comment by ole** [comment]
Auch wieder wahr. :)
