### ISSUE TITLE
Messe Velo Berlin

### ISSUE THREAD

**Issue by ole** [savoyhardwaregroup/speedometer#26]
Am letzten Aprilwochenende (27./28.4.) findet im Flughafen Tempelhof die Fahrradmesse [Velo Berlin](https://veloberlin.com) statt. Ich werde hingehen. Vielleicht hat von euch ja jemand Interesse mitzukommen (gerne auch mit Familie etc.)? Beim Tag (Samstag oder Sonntag) bin ich noch flexibel.

Für uns ist das ja quasi Konkurrenzbeobachtung. :-) Aber im Ernst: ich weiß nicht, ob es da viel in Sachen Dynamos und Fahrradcomputer zu sehen gibt. Aber der Eintritt ist recht günstig, es gibt einen Testparcours für Probefahrten und mich interessieren ein paar Aussteller.

Tickets gibt's im Vorverkauf auf der Website. Mit dem Code "urban" kostet ein Ticket 6 Euro (sonst 7, Tageskasse 9 Euro).

**Comment by NikolaiRuhe** [comment]
Oder wir machen einen kleinen Pop-Up Stand im Bauchladenformat. Nur die Prototypen kriegen wir wohl nicht vorher fertig.

Eigentlich gefällt mir unser Produkt immer besser: ein Kilometerzähler für die quantified-self Generation. Mit mobile App, die sich bei der Fahrt im Hintergrund synchronisiert und die gefahrenen Kilometer als Workout an die AppleWatch weitergibt. (Gibt es eigentlich eine API dafür?)
